### ISSUE TITLE
Bisq Connect Beta Release 0.2.0

### ISSUE THREAD

**Issue by rodvar** [bisq-network/bisq-mobile#190]
## Bisq Connect First Production Beta Release

 - [ ] update wiki with complete instructions on how to setup the http-api for production
 - [ ] update project docs to reflect the latest architectural changes, add link to releases at the top

**Comment by rodvar** [comment]
listing should be updated here once released:

 - https://github.com/bisq-network/bisq-mobile/wiki/How-to-use-Bisq-Connect-(WIP)

**Comment by rodvar** [comment]
moved to node milestone to close connect one

**Comment by rodvar** [comment]
check restoring iOS CI tests

```
name: BisqApps

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  # --- Common Build & Test (runs for all PRs, including forks) ---
  build:
    name: Build & Test (No Secrets)
    strategy:
      matrix:
        os: [ubuntu-latest, macos-14]  # MacOS for iOS tests, Ubuntu for general tests
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21 (Azul Zulu)
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'zulu'
          cache: gradle

      - name: Cache Gradle dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 33
          build-tools: 33.0.0

      - name: Set up Xcode (Mac only)
        if: startsWith(matrix.os, 'macos')
        run: |
          sudo xcode-select -s /Applications/Xcode_14.3.app
          xcodebuild -version

      - name: Create fake local.properties
        run: |
          echo "KEYSTORE_PATH=/path/to/keystore" > local.properties
          echo "KEYSTORE_PASSWORD=yourKeystorePassword" >> local.properties
          echo "KEY_ALIAS=yourKeyAlias" >> local.properties
          echo "CLI_KEY_ALIAS=yourCliKeyAlias" >> local.properties
          echo "KEY_PASSWORD=yourKeyPassword" >> local.properties
          echo "CLI_KEY_PASSWORD=yourCliKeyPassword" >> local.properties

      - name: Run androidClient Tests
        env:
          CI: true
        run: |
          ./gradlew androidClient:clean androidClient:assembleDebug --info
          ./gradlew androidClient:testDebugUnitTest androidClient:connectedDebugAndroidTest

      - name: Run iOS Tests
        if: startsWith(matrix.os, 'macos')
        run: ./gradlew shared:presentation:iosSimulatorArm64Test

  # --- Node-specific Maven build (needs secrets) ---
  node-maven:
    name: Node Build (Needs Secrets)
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name != 'pull_request' # skip for fork PRs

    env:
      CI: true
      MAVEN_URL: ${{ secrets.MAVEN_URL }}
      MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
      MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21 (Azul Zulu)
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'zulu'
          cache: gradle

      - name: Cache Gradle dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 33
          build-tools: 33.0.0

      - name: Build Node Project with Maven Secrets
        run: |
          ./gradlew androidNode:clean androidNode:bundleDebug --refresh-dependencies --info
          ./gradlew test

```
